title: Sarthak Goyal
logo: /assets/img/my_img.jpeg
description: I am a passionate web development enthusiast from India, dedicated to enhancing my skills through diverse projects. With a deep love for coding and a drive to tackle new challenges, I continuously seek to expand my expertise. Outside of web development, I enjoy photography as a hobby.
show_downloads: false
theme: jekyll-theme-minimal